from Validation.CTPPS.ctppsProtonReconstructionEfficiencyEstimatorData_cfi import *

from Configuration.Eras.Modifier_run3_common_cff import run3_common
run3_common.toModify(ctppsProtonReconstructionEfficiencyEstimatorData, useNewLHCInfo = True)

from Configuration.Eras.Modifier_run3_directSim_cff import run3_directSim
run3_directSim.toModify(ctppsProtonReconstructionEfficiencyEstimatorData, useNewLHCInfo = False)